print("Bem-vindo ao treinamento em Git!")
print("Hoje vamos aprender sobre versionamento de código.")
print("Git é uma ferramenta poderosa para desenvolvedores.")
print("Vamos começar com os comandos básicos!")
print("Estamos na branch da clara.")